console.log('715' == 715)
console.log('327' !== 327)
console.log('9' > 9 === false)
console.log('05' == 5)
console.log(null == undefined)
console.log(null != 0)
console.log(null >= 0)
console.log('0' == false)
console.log(0 == false)
console.log(isNaN(Number('942Number')))
console.log(String(942) === '942')
console.log(Number(true) === 1)
console.log(Number(false) === 0)
console.log(Number(null) === 0)
console.log(Number(' ') === 0)
console.log(Boolean(null) === false)
console.log(Boolean(' ') === true)
console.log(isNaN(Number(undefined)))
console.log(String(undefined) === 'undefined')
console.log(Boolean(undefined) === false)
console.log(Boolean(NaN) === false)
console.log(Boolean('') === false)
console.log(isNaN(Number('one')))
console.log(String([]) === '')
console.log(String({}) === '[object Object]')
console.log(Number([]) === 0)
console.log(isNaN(Number({})))
console.log(Boolean([]) === true)
console.log(Boolean({}) === true)